### ISSUE TITLE
Красивый notification

### ISSUE THREAD

**Issue by edgarshmavonyan** [Alexponomarev7/gate_sic_java#14]
В авторизации юзаются notification из antd. Хочется чтобы выглядело как здесь:
https://ant.design/components/notification/
(Нажать на кнопку любую там)
Пока что голым в html вставляется

**Comment by edgarshmavonyan** [comment]
Или возможно лучше как тут
https://www.callicoder.com/spring-boot-spring-security-jwt-mysql-react-app-part-2/

**Comment by Alexponomarev7** [comment]
Done.
