### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Alexponomarev7** [Alexponomarev7/gate_sic_java#5]
Мне кажется, что у нас что-то не так с REST API. Наш можно пощупать по 127.0.0.1:8080/api. Надо понять как норм это делают люди и пофиксить наш rest в инфре и в react.

**Comment by edgarshmavonyan** [comment]
По идее solved, пишем все на RestController-ах, на data rest не полагаемся

**Comment by edgarshmavonyan** [comment]
Example в MonitorController, к примеру
